# Site settings
title: Help With My Site
email: russellbeaman@gmail.com
description: Tailored Web Design & SEO Solutions in Raleigh, NC> # this means to ignore newlines until "baseurl:"
baseurl: "/helpwithmysite/" # the subpath of your site, e.g. /blog/
url: "https://rustisaurusrex.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
